# Generated by Django 4.1.7 on 2023-10-17 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeightRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('max_weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('min_weight', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
